server:
  port: 7777 #端口
spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: QWE123
    driver-class-name: com.mysql.cj.jdbc.Driver
  #文件上传
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  # redis配置
  redis:
    # Redis服务器地址
    host: 192.144.225.111
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池最大连接数
#        max-active: 150
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 5000ms
#        # 连接池中的最大空闲连接
#        max-idle: 100
#        # 连接池中的最小空闲连接
#        min-idle: 50

mybatis-plus:
  # mapper映射地址
  mapper-locations: classpath:mapper/*.xml
  # 实体类扫描包路径
  type-aliases-package: com.boke.domain.entity
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
# 文件上传策略 local、oss、cos
upload:
  # oss存储
  oss:
    url: http://verification.raydream.top/
    accessKey: v-I7gyTenKVIiMoJhnHdxjpFlVTFA7jcoXkPWfQg
    secretKey: NjfBxPELEcLXeSUpMKLkqh50Co0qEOZTEjspyp_p
    bucket: dreamy-blog
